version: "3.9"

name: fazi-ai

services:
  backend:
    image: evisolutions/fazi-ai-backend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    env_file:
      - ./.env
    volumes:
      - uploads:/app/uploads
      - data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: evisolutions/fazi-ai-frontend:latest
    ports:
      - "9234:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uploads:
  data:
