version: "3.9"

name: fazi-ai-old-repo

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      # You can override these via env_file or compose overrides
      # JWT_SECRET: replace-me
      # LOGIN_USERNAME: fazi-admin
      # LOGIN_PASSWORD: "#demo-transfer-uniform-collar!"
      # OPENAI_API_KEY: ""
    env_file:
      - ./.env
    volumes:
      - uploads:/app/uploads
      - data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_APP_API_BASE_URL: https://fazi.api.evi.rs
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  uploads:
  data:
