version: "3.9"

services:
  backend:
    container_name: ai-fazi-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      # You can override these via env_file or compose overrides
      # JWT_SECRET: replace-me
      # LOGIN_USERNAME: fazi-admin
      # LOGIN_PASSWORD: "#demo-transfer-uniform-collar!"
      # OPENAI_API_KEY: ""
    env_file:
      - ./.env
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
